config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  
  get "/realcraft200" => 'pages#realcraft_200'
  get 'about', to: 'pages#about', as: :about
  #get "prices", to: "pages#prices", as: :prices
  get "dealers", to: "pages#dealers", as: :dealers
  get 'realcraft190', to: 'pages#realcraft_190', as: :realcraft_190
  get 'realcraft200', to: 'pages#realcraft_200', as: :realcraft_200
  get 'realcraft440', to: 'pages#realcraft_440', as: :realcraft_440
  get 'realcraft470', to: 'pages#realcraft_470', as: :realcraft_470
  get "wait", to: 'pages#please_wait', as: :wait
  post "send_boat_request", to: 'pages#send_boat_request', as: :send_boat_request
  post "send_dealer_request", to: 'pages#send_dealer_request', as: :send_dealer_request
  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_boat_params_table.html.erb
<% 
    if @boat.nil? 
        canDrawTable = false
    else
        canDrawTable = !@boat[:boat_parameters].blank?
    end
%>
<%if canDrawTable %>
<% 
    mdfs = @boat[:modifications] 
%>
<div class = "row tb-pad-s">
    <div class = "small-12 columns">
        <h3 class = 'tb-pad-s'>
            <%= t :parameters_table %>
        </h3>
        <table class="hover">
            <thead>
            <tr>
                <th>
                    <%= t :parameter_name %>
                </th>
                <% mdfs.each do |m| %>
                    <th id = "modification">
                        <%= "#{@boat[:name]} #{m[:name] }"%>
                    </th>
                <% end %>
            </tr>
            </thead>
            <tr>
                <td>
                    <%= t :design_category %>
                </td>
                <td align = "center" colspan = "<%= mdfs.length %>">
                    <%= @boat[:design_category]%>
                </td>
            </tr>
            <% @boat[:boat_parameters].each do |p| %>
            <tr>
                <td>
                    <% if !p[:notice].blank? %> 
                        <span data-tooltip aria-haspopup="true" class="has-tip top" data-disable-hover="false" tabindex="2" title="<%= p[:notice] %>">
                            <%= p[:title] %> 
                        </span> 
                    <%else%>
                        <%= p[:title] %> 
                    <%end%>
                </td>
                <% if p[:value].class.name == "Array" %>
                    <% 0.upto(mdfs.length-1) do |i| %>
                        <td align = "center" >
                            <% if i < p[:value].length %>
                                <%= p[:value][i] %><%= p[:unit] %>
                            <% else %>
                                -
                            <%end%>
                        </td>
                    <%end%>
                <%else%>
                    <td align = "center" colspan = <%= mdfs.length %>>
                        <%= p[:value] %><%= p[:unit] %>
                    </td>
                <%end%>
            </tr>
            <%end%>
        </table>
    </div>
</div>
<%end%>

app/views/pages/_boat_request_form.html.erb
    <div class="reveal" data-reveal id = "boat-form-container">
        <div class = "tb-pad-s">
            <div class = "row">
                <div class = "small-10 small-centered columns">
                    <h4>
                        <%= t(:boat_request) %>
                    </h4>
                </div>
            </div>
            <div style = "display: none;" id = 'success-request' class = "row">
                <div class = "small-10 small-centered columns">
                    <div class = 'callout success'>
                    <p>
                        <i class = 'fi-check'></i> <%= t(:successfull_boat_request) %>
                    </p>
                   </div>
                </div>
            </div>
            <%= form_for(:boat_request, url: send_boat_request_path, html: {"data-abide"=> "", novalidate: "", remote: true}) do |f| %>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <div class = "row">
                            <div class = "small-12 medium-6 columns">
                                <%= f.label :email, "E-mail" %>
                                <%= f.email_field :email, placeholder: "name@domain.com", required: true  %>
                                <span class="form-error">
                                    <%= t(:fail_mail_msg)%>
                                </span>
                            </div>
                            <div class = "small-12 medium-6 columns">
                                <%= f.label :name, t(:mail_name) %>
                                <%= f.text_field :name, placeholder: t(:name_example), required: true  %>
                                <span class="form-error">
                                    <%= t(:mail_name_error)%>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <%= f.label :boat_name, t(:mail_boat) %>
                        <%= f.select :boat_name, boats_for_request_form if is_boat_page != true %>
                        <%= f.text_field :boat_name, readonly: '' if is_boat_page == true %>
                    </div>
                </div>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <%= f.label :comment, t(:mail_comment) %>
                        <%= f.text_area :comment, rows: 4 %>
                    </div>
                </div>
                <div class = 'row'>
                    <div class = "small-10 small-centered columns">
                        <%= f.submit t(:send_request_mail), class: "button success" %>
                    </div>
                </div>
            <% end %>
        </div>
        <button class="close-button" data-close type="button">
           <span aria-hidden="true">&times;</span>
        </button>
    </div>

app/views/pages/_boat_view_template.html.erb
<div class="orbit" role="region" aria-label="RealCraft Motor Boats" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
     <div class = "rc-fog medium-fog white-bg"><!-- Белая пелена над фотографией--></div> 
      <div id = "slogan">
            <div class = "row">
                <div class = "small-12 medium-6 large-5 columns">
                    <div class = " tb-pad-s"><%= rc_header(@boat[:name], t(:model), "#{t :design_category} #{@boat[:design_category]}")  %></div>
                    <p class = "show-for-large" title = "<%= @boat["header_description_#{cur_locale}".to_sym] %>">
                <%= truncate @boat["header_description_#{cur_locale}".to_sym], length: 380 %>
                    </p>
                </div>
                <div class = "medium-5 large-5 medium-offset-1 large-offset-2 columns hide-for-small-only">
                    <p id = "rc-boat-slogan" class = "text-center tb-pad-m hide-for-small">
                        <%= @boat["slogan_#{cur_locale}".to_sym] %>
                    </p>
                </div>
                <div class = "medium-1 columns hide-for-small-only">
                </div>
            </div>
      </div>
    <ul class="orbit-container">
        <%= slider_imgs(@boat[:slider_images]).html_safe  %>
    </ul>
</div> 
<% if !@boat["header_description_#{cur_locale}".to_sym].blank? %>
<div class = "c-box hide-for-large dark-blue-bg">
    <div class = "row tb-pad-s">
        <div class = "small-12 columns">
            <p>
                <%= @boat["header_description_#{cur_locale}".to_sym] %>
                
            </p>
        </div>
    </div>
</div>
<%end%>

<div id="rc-parameters" class = "white-text ">
    <div class = "tb-pad-m">
        <div class = "row">
            <div class = "small-12 columns">
                <h3 class = "text-center">
                    <%= t(:technical_information) %>
                </h3>
            </div>
        </div>
        <div class = "row row tb-pad-s">
            <% if !@boat[:main_params_big].blank?%>
                <% @boat[:main_params_big].each do |i|%>
                    <div class = "small-4 columns">
                        <p class = "rc-param-name-b text-center">
                            <%= @boat[:boat_parameters][i][:title] %>
                        </p>
                        <div class="stat text-center rc-param-val-b">
                            <%= @boat[:boat_parameters][i][:value] %><%= @boat[:boat_parameters][i][:unit] %>
                        </div>
                    </div>
                <%end %>
            <%end %>
        </div>
        <div class = "row">
            <% if !@boat[:main_params_small].blank?%>
                <% @boat[:main_params_small].each do |i|%>
                    <div class = "small-6 medium-4 large-2 columns tb-pad-s">
                        <p class = "rc-param-name-s text-center">
                            <%= @boat[:boat_parameters][i][:title] %>
                        </p>
                        <div class="stat text-center rc-param-val-s">
                            <%v = @boat[:boat_parameters][i][:value]%>
                            <%= v.class.name == "Array" ? "#{v.sort.first}-#{v.sort.last}" : v %><%= @boat[:boat_parameters][i][:unit] %>
                        </div>
                    </div>
                <%end %>
            <%end %>
        </div>
    </div>
</div>

<ul id = "rc-data-tabs" class="tabs" data-tabs data-deep-link="false" data-turbolinks="false" >
  <div class = "row">
          <li class="tabs-title small-6 medium-3 columns text-center is-active"><a class = 'no-style'  href="#modifications" aria-selected="true"><%= t(:modifications).mb_chars.upcase%></a></li>
          <li class="tabs-title small-6 medium-3 columns text-center"><a class = 'no-style' href="#engeneering"><%= t(:engeneering).mb_chars.upcase %></a></li>
          <li class="tabs-title small-6 medium-3 columns text-center"><a class = 'no-style' href="#photos"><%= t(:photos).mb_chars.upcase %></a></li>
          <li class="tabs-title small-6 medium-3 columns text-center"><a class = 'no-style' href="#videos"><%= t(:videos).mb_chars.upcase %></a></li>
  </div>
</ul>
<div class="tabs-content" data-tabs-content="rc-data-tabs">
  <div class="tabs-panel is-active" id="modifications">
    <div class="row tb-pad-s">
        <div class = "small-12 columns">
                <%= rc_header(t(:modifications), @boat[:name])  %>
        </div>
    </div>
    <div class="row tb-pad-s">
        <div class = "small-12 columns">
            <%= @boat["modifications_present_text_#{cur_locale}".to_sym ]%>
        </div>
    </div>
    <% if !@boat[:modifications].blank?  %>
        <%mCounter = 0%>
       <% @boat[:modifications].each do |m| %>
       <%mCounter += 1%>
                  <hr/>   
       <div class = "rc-modification-box tb-pad-s">
           <div class="row">
               <div class = "large-6 show-for-large end columns">
                   <h3><%= m[:name] %></h3>
                       <p>
                           <%= m["description_#{cur_locale}".to_sym] %>
                       </p>
               </div>
               <div class = "small-12 large-6 columns text-right">
                   <a data-open-boat-form = "<%= @boat[:name] %> <%= m[:name] %>" class = "button rc-primary-blue">
                       <%= t(:buy).mb_chars.upcase %>
                   </a>
               </div>
           </div>
           <div class = "row tb-pad-s">
               <div class = "small-12 medium-6 hide-for-large columns">
                   <h3><%= m[:name] %></h3>
                   <% if !m["description_#{cur_locale}".to_sym].blank? %>
                       <p>
                           <%= m["description_#{cur_locale}".to_sym] %>
                       </p>
                   <% end %>
               </div>
               <% m[:model_view_imgs].each do |i|%>
                   <div class = "small-12 medium-6 large-4 columns">
                       
                       <div style = "position: relative;"><div style = "position: absolute; top: 10px; right: 10px; z-index:200;"><h7><%= i[:title] %></h7></div></div>
                       <a><%= image_tag i[:url], class: "kra-ph-box", "rc-box-phs".to_sym => "[#{i[:url]}, small]", "rc-box-collection".to_sym => "boat-views-#{mCounter}", "rc-box-title".to_sym => "#{@boat[:name]} #{m[:name]}: #{i[:title]}"  %></a>
                   </div>
               <%end%>
           </div>
           <% unless m[:acc_views_imgs].blank? %>
           <div class = "row">
               <div class = "small-12 columns">
               <h5>
                   <%= t(:crew_accomodation).mb_chars.upcase %>
               </h5>
               </div>
           </div>
           <div class = "row tb-pad-s">
               <div class = "medium-12 large-2 columns">
                   <%=  t(:crew_accomodation_txt, modification: "<b>#{m[:name]}</b>", crew_limit: searchRCParamValByTitle(t(:crew_limit))[:value].to_i.to_s).html_safe  %>
               </div>
               <% j=0 %>
               <% m[:acc_views_imgs].each do |i|%>
                   <%j+=1%>
                   <div class = "small-12 medium-6 large-5 columns">
                       <h7><%= t(:scheme) %> <%= j.to_s %></h7>
                       <%= image_tag i %>
                   </div>
               <%end%>
           </div>
           <%end %>
           <%unless m[:arrangement_img].blank? %>
           <div class = "row tb-pad-s">
               <div class = "small-12 columns">
                   <%= image_tag m[:arrangement_img] %>
               </div>
           </div>
           <%end%>
           </div>
 
       <%end%> 
    <%end%>


  </div>

  <div class="tabs-panel" id="engeneering">
    <div class = "tb-pad-s">
        <div class = "row">
            <div class = "small-12 columns">
                <%= rc_header(t(:engeneering), @boat[:name])  %>
            </div>
        </div>
        <%unless @boat[:engeneering_img].blank? || @boat["engeneering_text_#{cur_locale}".to_sym].blank? %>
        <div class = "row">
            <div class = "small-12 medium-5 columns tb-pad-s">
                <p>
                    <%= @boat["engeneering_text_#{cur_locale}".to_sym] %>
                </p>
            </div>
            <div class = "small-12 medium-7 columns tb-pad-s">
                <%= image_tag @boat[:engeneering_img] %>            
            </div>
        </div>
        <%end%>
        <%= render "boat_params_table" %>
    </div>
  </div>
  <div class="tabs-panel" id="photos">
    <div class = "tb-pad-s">
        <div class = "row">
            <div class = "small-12 columns">
                <%= rc_header(t(:photos), @boat[:name])  %>
            </div>
        </div>
        
            <% if @boat[:photos].blank? %>
            <div class = "row tb-pad-m">
                <div class = "small-12 columns">
                    <p>
                        <%= t(:no_photos_msg) %>
                    </p>
                </div>
            </div>
            <% else %>
            <div class="row small-up-2 medium-up-2 large-up-3">
                <% @boat[:photos].each do |p| %>
                  <div class="column column-block tb-pad-s">
                        <a><%= image_tag p[:thumbnail], class: "float-center kra-ph-box", "rc-box-phs".to_sym => "[#{p[:small]}, small], [#{p[:medium]}, medium], [#{p[:large]}, large], [#{p[:xlarge]}, xlarge]", "rc-box-collection".to_sym => "boat-photos" %></a>
                  </div>
                <%end%>
            </div>
            <%end%>
        
    </div>
  </div>
  <div class="tabs-panel" id="videos">
    <div class = "tb-pad-s">
        <div class = "row">
            <div class = "small-12 columns">
                <%= rc_header(t(:videos), @boat[:name])  %>
            </div>
        </div>
        <% if @boat[:videos].blank? %>
            <div class = "row tb-pad-m">
                    <div class = "small-12 columns">
                        <p>
                            <%= t(:no_videos_msg) %>
                        </p>
                    </div>
            </div>
        <%else%>
            <% @boat[:videos].each do |v|%>
            <div class = "row tb-pad-s">
                <div class = "small-12 medium-8 large-7 small-centered columns">
                    <div class="flex-video widescreen">
                      <%= v.html_safe %>
                    </div>
                </div>
            </div>
            <%end%>
        <%end%>
    </div>
  </div>
</div>

<%= render "boat_request_form", is_boat_page: true %>

app/views/pages/_footer.html.erb
<div class = "light-gray-block">
    <div id = "footer" class = "row tb-pad-m">
        <div id = "footer-logo" class = "small-12 medium-5 columns">
            <div class = "row">
                <div class = "small-12 small-push-12 medium-push-0 columns">
                   <%= image_tag "logo_colorful.png" %>
                </div>
            </div>
            <div class = "row tb-pad-m">
                <div class = "small-12 small-pull-12 medium-pull-0 columns">
                    REALCRAFT™, 2014-<%= Time.now.year.to_s %> 
                </div>
            </div>
        </div>
        <div id = "footer-contacts"  class = "small-12 medium-offset-1 medium-6 columns">
            <h4>
                <%= t(:contacts) %>
            </h4>
            <p>
                <% if cur_locale == :en%>
                Samara Motor-Boat Plant «Salut» (Salut-boats Ltd),<br />
                Sovetskaya str., 38L, Novosemeykino urban-type settlement, Krasnoyarskiy district,<br />
                Samara region, Russia, 446379, <br />
                Tel.:  +7-846-9726801, +7-846-277210<br />
                <%else%>
                Самарский завод моторных лодок «СAЛЮТ»,<br />
                Россия, 446379, Самарская область, Красноярский район,<br />
                пгт. Новосемейкино, ул. Советская, д. 38л<br />
                Тел.:  +7-846-9726801, +7-846-277210<br />
                <%end%>
                <%= link_to t(:self_url_name), root_path %><br />
                <%= mail_to "info@realcraftboats.com", "info@realcraftboats.com" %>
            </p>
        </div>
    </div>

</div>

app/views/pages/_simple_pages_content.html.erb
<%if !content.blank? %>
    <% content.each do |row| %>
        <div <%= row[:is_hidden] == true ? "style=display:none;" : "" %> <%= row[:wrapper_bg_image].blank? ? "" : "data-interchange = '#{make_photos_interchange(wrapper_bg_image(row[:wrapper_bg_image]))}' style = 'background-image: url(\"#{wrapper_bg_image(row[:wrapper_bg_image])}\");'".html_safe %> class = "c-box <%= row[:wrapper_class].blank? ? "" : "#{row[:wrapper_class]}" %>">
            <% if !row[:fog_class].blank? %>
                <div class = "rc-fog <%= row[:fog_class] %>">
                </div>
            <% end %>
            <div style = 'position: relative; z-index:  500;' class = "row <%= row[:row_class].nil? ? "" : row[:row_class] %>">
                <%if !row[:columns].empty?%>
                    <%row[:columns].each do |c|%>
                        <div class = "<%= c[:col_class].blank? ? "small-12" : c[:col_class] %> columns">
                            <p>
                                <%= c["#{cur_locale}_content".to_sym].html_safe if !c["#{cur_locale}_content".to_sym].blank? %>
                                <%= c[:content].html_safe if !c[:content].blank? %>
                            </p>
                        </div>
                    <%end%>
                <%end%>
            </div>
        </div>
    <%end%>
<%end%>

app/views/pages/dealers.html.erb
<div class = "tb-pad-s">
    <div class = "row">
        <div class = "small-12 columns">
            <%= rc_header(t(:dealers))  %>
        </div>
    </div>
</div>
<%= draw_dealers_list.html_safe %>
<%= render "simple_pages_content", content: dealers_page_content %>

<div id = "boat-request-form" style = 'display: none;'>
    <%= render "dealer_request_form" %>
</div>

app/views/pages/index.html.erb
<div class="orbit" role="region" aria-label="RealCraft Motor Boats" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
  <div id = "slogan">
      <div class = 'row tb-pad-s' style = " position: relative;margin-left: auto; margin-right: auto;">
         <div class = "small-12 columns">
             <img id = "slogan-img" src = "/files/main_slogan.png">
         </div>
      </div>
  </div>
    <div class="orbit-container">
      <%= slider_imgs(main_page_slider_imgs).html_safe  %>
    </div>
</div> 
<div class = "light-gray-block">
    <div class = 'row'>
        <div class = 'small-12 columns tb-pad-s'>
            <a href = "/files/Realcraft.pdf" target = '_blank' class = 'button rc-blue expanded' style = "margin: 0 0 0 0;"><i class = 'fi-download'></i> <%= t(:download_brochure).mb_chars.upcase %></a>
        </div>
    </div>
</div>  
<!--boats list-->
<% if !hash_boats_list.blank?%>
    <%j=0%>
    <% hash_boats_list.each do |b|%>
    <%j+=1%>
    <div class = "pages-index-boat-item ">
        <div class = "<%= j.odd? ? "odd" : "even"  %>-wrapper"></div>
        <div class = "content tb-pad-s">
            <div class = "row tb-pad-s">
                <div class = "small-12 medium-5 columns">
                    <%= rc_header(b[:name], t(:model), "#{t :design_category} #{b[:design_category]}") %>
                </div>
                <div class = "small-12 medium-7 columns">
                    <% if !b[:index_page_parameters].blank?%>
                        <div class = "row">
                        <% b[:index_page_parameters].each do |i|%>
                            <div class = "small-4 columns params-list">
                                <p class = "rc-param-name-s text-center">
                                    <%= b[:boat_parameters][i][:title] %>
                                </p>
                                <div class="stat text-center rc-param-val-s">
                                    <%= b[:boat_parameters][i][:value] %><%= b[:boat_parameters][i][:unit] %>
                                </div>
                            </div>
                        <%end %>
                        </div>
                    <%end %>
                </div>
            </div>
            <div class = "row">
                <div class = "small-12 columns text-center">
                    <p >
                        <%= b["slogan_#{cur_locale}".to_sym] %>
                    </p>
                </div>
            </div>
            <div class = "row tb-pad-s">
                <div class = "small-12 columns">
                    <%= image_tag b[:slider_images].first, "data-interchange".to_sym => make_photos_interchange(b[:slider_images].first), style: "padding:0; margin:0;", vspace: "0" %>
                    <div class = "tb-pad-s">
                    <%= link_to ("<i class = \"fi-arrow-right\"></i> #{t(:go_to_item, item: b[:name])}").html_safe, b[:url], class: "rc-primary-blue button expanded large" %>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
    <%end%>
<%end%>
<!--boats list end-->
<div class = "light-blue-block">
    <div class = "tb-pad-m">
        <div class = "row">
            <div class = "small-12 columns text-center">
                <%= rc_header(t(:we_are), t(:who)) %>
            </div>
        </div>
        <div class = "row">
            <div class = "small-12 medium-4 columns">
                <p class = "stat text-center">
                     15,000 <%= t :m_short %><span class = "degree">2</span>
                 </p>
                 <p class = "rc-param-name-b text-center">
                     <%= t :land_for_production %>
                 </p>
                 <a><%= image_tag production_photos("6")[:url], class: "kra-ph-box", "rc-box-phs".to_sym => production_photos("6")[:list], "rc-box-collection".to_sym => "production"  %></a>
            </div>
            <div class = "small-12 medium-4 columns tb-pad-s">
                    <a><%= image_tag production_photos("2")[:url], class: "kra-ph-box tb-pad-s", "rc-box-phs".to_sym => production_photos("2")[:list], "rc-box-collection".to_sym => "production"  %></a>
                    <p class = "stat text-center">
                         <%= Time.now.year.to_i - 2004 %> <%= t :years %>
                     </p>
                     <p class = "rc-param-name-b text-center">
                         <%= t :experience_of_shipbuilding %>
                     </p>
                     <p class = "text-center">
                         <%= link_to "#{t(:more).mb_chars.capitalize}...", about_path %>
                     </p>
            </div>
            <div class = "small-12 medium-4 columns">
                <p class = "stat text-center">
                     3,800 <%= t :m_short %><span class = "degree">2</span>
                 </p>
                 <p class = "rc-param-name-b text-center">
                     <%= t :production_and_warehouse_space %>
                 </p>
                 <a><%= image_tag production_photos("1")[:url], class: "kra-ph-box", "rc-box-phs".to_sym => production_photos("1")[:list], "rc-box-collection".to_sym => "production"  %></a>
            </div>    
        </div>
    </div>

</div>

app/views/pages/please_wait.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:default_title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
      <div class = "row tb-pad-s">
          <div class = "small-12 small-centered columns">
              <%= image_tag "logo_vertical_colored.png", style: "height: 150px;", class: "float-center" %>
          </div>
          
      </div>
      <div class = "row tb-pad-s">
          <div class = "small-12 medium-offset-1 medium-5 columns">
              <div class="flex-video widescreen">
              <iframe width="496" height="279" src="https://www.youtube.com/embed/fxN92HTzx4U" frameborder="0" allowfullscreen></iframe>
              </div>
          </div>
          <div class = "small-12 medium-5 end columns">
              <div class="flex-video widescreen">
              <iframe width="496" height="279" src="https://www.youtube.com/embed/J0JQXQbo01M" frameborder="0" allowfullscreen></iframe>
              </div>
          </div>
      </div>
      <div class = "row">
          <div class = "small-11 small-centered columns text-center">
             <h4 class = "float-center"><%= t(:coming_soon) %>...</h4>
          </div>
      </div>
  </body>
</html>

app/views/pages/prices.html.erb
<div class = "tb-pad-s">
    <div class = "row">
        <div class = "small-12 columns">
            <%= rc_header(t(:prices))  %>
        </div>
    </div>
</div>

<%= render "simple_pages_content", content: prices_page_content %>
<div id = "boat-request-form" style = 'display: none;'>
    <%= render "boat_request_form", is_boat_page: false %>
</div>

app/views/pages/realcraft_190.html.erb
<%= render "boat_view_template" if !@boat.nil? %>

app/views/pages/realcraft_200.html.erb
<%= render "boat_view_template" %>

app/views/pages/realcraft_440.html.erb
<%= render "boat_view_template" if !@boat.nil? %>

app/views/pages/realcraft_470.html.erb
<%= render "boat_view_template" if !@boat.nil? %>