config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  
  get "/realcraft200" => 'pages#realcraft_200'
  get 'about', to: 'pages#about', as: :about
  #get "prices", to: "pages#prices", as: :prices
  get "dealers", to: "pages#dealers", as: :dealers
  get 'realcraft190', to: 'pages#realcraft_190', as: :realcraft_190
  get 'realcraft200', to: 'pages#realcraft_200', as: :realcraft_200
  get 'realcraft440', to: 'pages#realcraft_440', as: :realcraft_440
  get 'realcraft470', to: 'pages#realcraft_470', as: :realcraft_470
  get "wait", to: 'pages#please_wait', as: :wait
  post "send_boat_request", to: 'pages#send_boat_request', as: :send_boat_request
  post "send_dealer_request", to: 'pages#send_dealer_request', as: :send_dealer_request
  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title.blank? ? t(:default_title) : @title %></title>
    <meta name = 'description' content = '<%= @meta_content.nil? ? t(:default_meta_description) : @meta_content %>' >
    <meta name = 'keywords' content = '<%= @meta_keywords.nil? ? t(:default_meta_keywords)  : @meta_keywords %>' >
    <meta property="og:title" content="<%= @title.blank? ? t(:default_title) : @title %>">
    <meta property="og:image" content="<%= @page_image.nil? ? '/slider/rc200/4_slider_small.jpg' : @page_image %>">
    <meta property="og:description" content="<%= @meta_content.nil? ? t(:default_meta_description) : @meta_content %>">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
      <script> 
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ 
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), 
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) 
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); 

      ga('create', 'UA-98011229-1', 'auto'); 
      ga('send', 'pageview'); 

      </script>
      <!-- Yandex.Metrika counter -->
      <script type="text/javascript">
          (function (d, w, c) {
              (w[c] = w[c] || []).push(function() {
                  try {
                      w.yaCounter42383514 = new Ya.Metrika({
                          id:42383514,
                          clickmap:true,
                          trackLinks:true,
                          accurateTrackBounce:true,
                          webvisor:true
                      });
                  } catch(e) { }
              });

              var n = d.getElementsByTagName("script")[0],
                  s = d.createElement("script"),
                  f = function () { n.parentNode.insertBefore(s, n); };
              s.type = "text/javascript";
              s.async = true;
              s.src = "https://mc.yandex.ru/metrika/watch.js";

              if (w.opera == "[object Opera]") {
                  d.addEventListener("DOMContentLoaded", f, false);
              } else { f(); }
          })(document, window, "yandex_metrika_callbacks");
      </script>
      <noscript><div><img src="https://mc.yandex.ru/watch/42383514" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
      <!-- /Yandex.Metrika counter -->
      <div id = "header" data-turbolinks-permanent>
          <div id = "responsive" class="title-bar row" data-responsive-toggle="main-menu" data-hide-for="medium">
              <div class = "small-8 columns">
                  <button class="menu-icon" type="button" data-toggle></button>
                  <div class="title-bar-title">
                      <div class="top-bar-left">
                          <ul class = 'menu'>
                              <li>
                                  <%= link_to image_tag("/files/white_logo.png", style: "height: 30px;").html_safe, root_path %>
                              </li>
                          </ul>
                      </div>
                  </div>
              </div>
              <div class = "small-4 columns">
                  <div class="top-bar-right">
                      <ul class = 'menu'>
                          <li  id = "locale-link">
                              <%= link_to t(:opposite_locale_name), opposite_locale_url, class: "locale-link" if is_all_locales_enabled? %>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
          <div class="top-bar" id = "main-menu" data-animate="hinge-in-from-top spin-out">
              <div class = "row">
                  <div class = "small-12 columns">
                      <ul class="dropdown menu expanded" data-dropdown-menu>
                        <li class="top-bar-img hide-for-small-only" > 
                            <%= link_to image_tag("/files/white_logo.png", style: "max-height: 35px;").html_safe, root_path %>
                        </li>
                        <li class = "top-bar-links text-center">
                            <%= link_to t(:products), "#" %>
                            <ul class = "menu">
                                <li>
                                    <%= link_to "RealCraft 190", realcraft_190_path %>
                                </li>
                                <li>
                                    <%= link_to "RealCraft 200", realcraft_200_path %>
                                </li>
                                <% if is_ru? %>
                                    <li>
                                        <%= link_to "RealCraft 440", realcraft_440_path %>
                                    </li>
                                    <li>
                                        <%= link_to "RealCraft 470", realcraft_470_path %>
                                    </li>
                                <% end %>
                            </ul>
                        </li>
                        <% if is_ru? %> 
                            <li class = "top-bar-links text-center">
                                <a target = '_blank' href = 'http://www.salut-boats.ru/configurator/?lfb_action=preview&form=20000'>
                                    <%= t(:prices) %>
                                </a>
                                    <%# link_to t(:prices), 'www.salut-boats.ru/configurator/?lfb_action=preview&form=20000' %>
                            </li> 
                        <%end%>
                        <li class = "top-bar-links text-center"><%= link_to t(:dealers), dealers_path %></li>
                        <li class = "top-bar-links text-center">
                            <%= link_to t(:about), about_path %>
                        </li>
                        <li class = "top-bar-links text-center">
                            <a onclick = "$('html, body').animate({ scrollTop: $('#footer').offset().top}, 1000);">
                                <%= t(:contacts) %>
                            </a>
                        </li>                    
                        <li class = "top-bar-links text-right hide-for-small-only">
                            <%= link_to t(:opposite_locale_name), opposite_locale_url, class: "locale-link" if is_all_locales_enabled? %>
                        </li>
                      </ul>
                  </div>
              </div>
                    
          </div>
      </div>
    <%= yield %>
    <%= render "pages/footer" %>
  </body>
</html>